// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.IO;

namespace PayrollProject
{
    public partial class MasterPageAccess
    {
        private static IMasterPageAccessPersister _DefaultPersister;
        private IMasterPageAccessPersister _Persister;
        private int _MasterPageID;
        private int? _StaffID;
        private int? _CompID;
        private int? _ModuleID;
        private string _RoleName;

        static MasterPageAccess()
        {
            // Assign default persister
            _DefaultPersister = new SqlServerMasterPageAccessPersister();
        }

        public MasterPageAccess()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 
        }

        public MasterPageAccess(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 

            // Assign column values to private members
            for (int  i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "MASTERPAGEID":
                        this.MasterPageID = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        break;
                    
                    case "STAFFID":
                        if(row.IsNull(i) == false)
                        {
                            this.StaffID = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        }
                        break;
                    
                    case "COMPID":
                        if(row.IsNull(i) == false)
                        {
                            this.CompID = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        }
                        break;
                    case "MODULEID":
                        if (row.IsNull(i) == false)
                        {
                            this.ModuleID = Convert.ToInt32(row[i, DataRowVersion.Current]);
                        }
                        break;
                    case "ROLENAME":
                        if (row.IsNull(i) == false)
                        {
                            this.RoleName = row[i, DataRowVersion.Current].ToString() ;
                        }
                        break;
                }
            }
        }

        public static IMasterPageAccessPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public IMasterPageAccessPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public int MasterPageID
        {
            get { return _MasterPageID; }
            set { _MasterPageID = value; }
        }

        public int? StaffID
        {
            get { return _StaffID; }
            set { _StaffID = value; }
        }

        public int? CompID
        {
            get { return _CompID; }
            set { _CompID = value; }
        }

        public int? ModuleID
        {
            get { return _ModuleID; }
            set { _ModuleID = value; }
        }

        public String RoleName
        {
            get { return _RoleName; }
            set { _RoleName = value; }
        }
        public virtual void Clone(MasterPageAccess sourceObject)
        {
            // Clone attributes from source object
            this._MasterPageID = sourceObject.MasterPageID; 
            this._StaffID = sourceObject.StaffID; 
            this._CompID = sourceObject.CompID;
            this._ModuleID = sourceObject.ModuleID;
            this._RoleName = sourceObject.RoleName; 
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this); 
        }

        public static IReader<MasterPageAccess> ListAll()
        {
            return _DefaultPersister.ListAll(); 
        }

        public static IReader<MasterPageAccess> ListForMasterPageID(int masterPageID)
        {
            return _DefaultPersister.ListForMasterPageID(masterPageID); 
        }

    }
    
    public partial interface IMasterPageAccessPersister
    {
        int Insert(MasterPageAccess masterPageAccess);
        IReader<MasterPageAccess> ListAll();
        IReader<MasterPageAccess> ListForMasterPageID(int masterPageID);
    }
    
    public partial class SqlServerMasterPageAccessPersister : SqlPersisterBase, IMasterPageAccessPersister
    {
        public SqlServerMasterPageAccessPersister()
        {
        }

        public SqlServerMasterPageAccessPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServerMasterPageAccessPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServerMasterPageAccessPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Insert(MasterPageAccess masterPageAccess)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("MasterPageAccessInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Add command parameters
                SqlParameter vMasterPageID = new SqlParameter("@MasterPageID", SqlDbType.Int);
                vMasterPageID.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vMasterPageID);
                SqlParameter vStaffID = new SqlParameter("@StaffID", SqlDbType.Int);
                vStaffID.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vStaffID);
                SqlParameter vCompID = new SqlParameter("@CompID", SqlDbType.Int);
                vCompID.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vCompID);
                SqlParameter vModuleID = new SqlParameter("@ModuleID", SqlDbType.Int);
                vModuleID.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vModuleID);
                SqlParameter vRoleName = new SqlParameter("@RoleName", SqlDbType.Char );
                vRoleName.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vRoleName);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vMasterPageID, masterPageAccess.MasterPageID);
                SqlServerHelper.SetParameterValue(vStaffID, masterPageAccess.StaffID);
                SqlServerHelper.SetParameterValue(vCompID, masterPageAccess.CompID);
                SqlServerHelper.SetParameterValue(vModuleID, masterPageAccess.ModuleID);
                SqlServerHelper.SetParameterValue(vRoleName, masterPageAccess.RoleName);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 
                    if(__rowsAffected == 0)
                    {
                        return __rowsAffected; 
                    }
                    

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public IReader<MasterPageAccess> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("MasterPageAccessListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServerMasterPageAccessReader(reader); 
            }
        }

        public IReader<MasterPageAccess> ListForMasterPageID(int masterPageID)
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("MasterPageAccessListForMasterPageID"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Add command parameters
                SqlParameter vMasterPageID = new SqlParameter("@MasterPageID", SqlDbType.Int);
                vMasterPageID.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vMasterPageID);
                
                // Set input parameter values
                SqlServerHelper.SetParameterValue(vMasterPageID, masterPageID);

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServerMasterPageAccessReader(reader); 
            }
        }

    }

    public partial class SqlServerMasterPageAccessReader : IReader<MasterPageAccess>
    {
        private SqlDataReader sqlDataReader;

        private MasterPageAccess _MasterPageAccess;

        private int _MasterPageIDOrdinal = -1;
        private int _StaffIDOrdinal = -1;
        private int _CompIDOrdinal = -1;
        private int _ModuleIDOrdinal = -1;
        private int _RoleNameOrdinal = -1;

        public SqlServerMasterPageAccessReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader; 
            for (int  i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper(); 
                switch (columnName)
                {
                    case "MASTERPAGEID":
                        _MasterPageIDOrdinal = i; 
                        break;
                    
                    case "STAFFID":
                        _StaffIDOrdinal = i; 
                        break;
                    
                    case "COMPID":
                        _CompIDOrdinal = i; 
                        break;

                    case "MODULEID":
                        _ModuleIDOrdinal = i;
                        break;

                    case "ROLENAME":
                        _RoleNameOrdinal = i;
                        break;
                }
            }
        }

        #region IReader<MasterPageAccess> Implementation
        
        public bool Read()
        {
            _MasterPageAccess = null; 
            return this.sqlDataReader.Read(); 
        }

        public MasterPageAccess Current
        {
            get
            {
                if(_MasterPageAccess == null)
                {
                    _MasterPageAccess = new MasterPageAccess();
                    if(_MasterPageIDOrdinal != -1)
                    {
                        _MasterPageAccess.MasterPageID = SqlServerHelper.ToInt32(sqlDataReader, _MasterPageIDOrdinal); 
                    }
                    _MasterPageAccess.StaffID = SqlServerHelper.ToNullableInt32(sqlDataReader, _StaffIDOrdinal); 
                    _MasterPageAccess.CompID = SqlServerHelper.ToNullableInt32(sqlDataReader, _CompIDOrdinal);
                    _MasterPageAccess.ModuleID = SqlServerHelper.ToNullableInt32(sqlDataReader, _ModuleIDOrdinal);
                    _MasterPageAccess.RoleName = SqlServerHelper.ToString(sqlDataReader, _RoleNameOrdinal); 
                }
                

                return _MasterPageAccess; 
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<MasterPageAccess> ToList()
        {
            List<MasterPageAccess> list = new List<MasterPageAccess>();
            while(this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list; 
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable; 
        }

        #endregion
        
        #region IDisposable Implementation
        
        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion
        
        #region IEnumerable<MasterPageAccess> Implementation
        
        public IEnumerator<MasterPageAccess> GetEnumerator()
        {
            return new MasterPageAccessEnumerator(this); 
        }

        #endregion
        
        #region IEnumerable Implementation
        
        IEnumerator IEnumerable.GetEnumerator()
        {
            return new MasterPageAccessEnumerator(this); 
        }

        #endregion
        
        
        private partial class MasterPageAccessEnumerator : IEnumerator<MasterPageAccess>
        {
            private IReader<MasterPageAccess> masterPageAccessReader;

            public MasterPageAccessEnumerator(IReader<MasterPageAccess> masterPageAccessReader)
            {
                this.masterPageAccessReader = masterPageAccessReader; 
            }

            #region IEnumerator<MasterPageAccess> Members
            
            public MasterPageAccess Current
            {
                get { return this.masterPageAccessReader.Current; }
            }

            #endregion
            
            #region IDisposable Members
            
            public void Dispose()
            {
                this.masterPageAccessReader.Dispose();
            }

            #endregion
            
            #region IEnumerator Members
            
            object IEnumerator.Current
            {
                get { return this.masterPageAccessReader.Current; }
            }

            public bool MoveNext()
            {
                return this.masterPageAccessReader.Read(); 
            }

            public void Reset()
            {
                throw new Exception("Reset of masterpageaccess reader is not supported."); 
            }

            #endregion
            
        }
    }
}
